Fix #14 add proper Readme for the project
softgitron/potku-console pull request #15
Opened 2021-06-01 16:38 UTC by softgitron

Closes #14. First draft for a better README. Comments welcome!

2021-06-05 17:29 UTC, EddieTheCubeHead requested changes
Left comments with typos, mistakes and suggestions. Suggestios are optional, but won't approve before the typos and mistakes are fixed.

2021-06-05 17:29 UTC, EddieTheCubeHead commented on README.md
> +Potku-console is a service control platform that is user for starting services automatically on demand. Potku-console consists of different kind of modules like: core, frontend, service modules and c
...that is useD for...
...consists of different kindS of modules...
Maybe remove the like before module listing, IMO would make the sentence flow better.
...especially on THE core and frontend parts...
Maybe remove the also from last sentence and add "as well" to the end.

2021-06-05 17:29 UTC, EddieTheCubeHead commented on README.md
> +You would like to own a (insert game name here) server where you and your group of Discord friend could play together. You would like to have server with multiple cores and decent amount of RAM from
...own aN (insert game here)...
...group of Discord friendS could...
...like to have A server with multiple cores and A decent amount...
Maybe replace "Seek" in "seek for a" with "search" or "look".
...due to A tight budget...
...At first THE idea felt good...
Maybe replace "time regions" with "time zones".
...and they like to PLAY ON THE SERVER even after you HAVE gone to sleep...
Making use of "if only" in the last sentence would be more natural IMO, ie: "if only there was an easy way..."

2021-06-05 17:29 UTC, EddieTheCubeHead commented on README.md
> +Yes there is a solution, it is called potku-console. Potku-console monitors automatically player counts on the server and shuts it down after last player has left the game. After the server has been
...Potku-console AUTOMATICALLY MONITORS player counts...
...after THE last player...
...potku-console sets A guard...
...for the server's address... (missing apostrophe)
...waits for new players... (no THE with plural form)
...when THE first player...
...saves A ton of money... OR ...saves tonS of money...

2021-06-05 17:29 UTC, EddieTheCubeHead commented on README.md
> +Potku-console uses following technologies:
...uses THE following...

2021-06-05 17:29 UTC, EddieTheCubeHead commented on README.md
> +More information about [potku-console architecture](https://github.com/softgitron/potku-console/wiki/Components-overview) can be found from project's wiki.
...found from THE project's wiki...

2021-06-05 17:29 UTC, EddieTheCubeHead commented on README.md
> +Awesome to see that you are interested to make this project even better! We are open for all improvements and contributions. See [Contributing wiki-page](https://github.com/softgitron/potku-console/w
...interested IN MAKING this...
...for basic instructionS.

2021-06-05 17:35 UTC, EddieTheCubeHead commented on README.md
> +Yes there is a solution, it is called potku-console. Potku-console monitors automatically player counts on the server and shuts it down after last player has left the game. After the server has been
no THE with plural form is not grammatically correct advice btw, my bad. The "the" doesn't belong there, but plurality has nothing to do with it.

2021-06-06 12:21 UTC, softgitron commented
Thanks for a great review Eddie! I accepted all of your proposals and pushed a new [commit](https://github.com/softgitron/potku-console/pull/15/commits/bc5ab17d6c0a9d21c3908abc45e10f372899e3a5). I have always been especially bad with articles, so it came to me as no surprise that there are a ton of article errors. It is still excellent to get those errors fixed especially on Readme, so that our users don't get irritated at once, when they open our repository's front page.

2021-06-07 17:05 UTC, EddieTheCubeHead approved these changes

2021-06-08 15:38 UTC, merged